# Audio-Only Drama — Automated FX Engine
# Docker Compose configuration for development services

version: '3.8'

services:
  # PostgreSQL database for storing application data
  postgres:
    image: postgres:16
    container_name: audio-drama-postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: fx
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d fx"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - audio-drama-network

  # Redis for caching and task queue
  redis:
    image: redis:7-alpine
    container_name: audio-drama-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - audio-drama-network

  # Optional: Redis Commander for Redis management UI
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: audio-drama-redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - audio-drama-network
    profiles:
      - tools

  # Optional: pgAdmin for PostgreSQL management UI
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: audio-drama-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@audio-drama.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - audio-drama-network
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  audio-drama-network:
    driver: bridge
